import { create } from 'zustand';
import { ensureAllDuaCategoriesLoaded, hydrateDuaCategories, loadDuaCategorySummaries, type LoadedDuaCategory } from '@/content/loaders/load-duas';
import type { DuaCategory, DuasState, PersistedDuasState } from '@/features/duas/domain/dua-types';
import { LocalStorageEngine } from '@/kernel/storage/local-storage-engine';
import { STORAGE_KEYS } from '@/kernel/storage/storage-keys';
import { getLocalDateKey, trimRecordToRecentDays } from '@/shared/lib/date';
interface DuasStore extends DuasState { initialize: () => void; ensureLoaded: () => Promise<void>; setSearchQuery: (query: string) => void; setSelectedCategory: (slug: string) => void; toggleItemCompleted: (itemId: string) => void; toggleFavorite: (itemId: string) => void; resetTodayProgress: () => void; }
const storage = new LocalStorageEngine();
const fallbackPersistedState: PersistedDuasState = { selectedCategorySlug:null, searchQuery:'', completedByDate:{}, favoriteIds:[], recentCategorySlugs:[] };
const fallbackState: DuasState = { ...fallbackPersistedState, isInitialized:false, isLoading:false, error:null, categories:[] };
function normalizePersistedState(rawValue: PersistedDuasState | null): PersistedDuasState { if(!rawValue) return fallbackPersistedState; return { selectedCategorySlug: rawValue.selectedCategorySlug ? String(rawValue.selectedCategorySlug) : null, searchQuery:String(rawValue.searchQuery ?? ''), completedByDate: trimRecordToRecentDays(Object.fromEntries(Object.entries(rawValue.completedByDate ?? {}).map(([dateKey, ids])=>[dateKey,[...new Set(Array.isArray(ids) ? ids.filter(Boolean) : [])]])),180), favoriteIds:Array.isArray(rawValue.favoriteIds) ? [...new Set(rawValue.favoriteIds.map((item)=>String(item).trim()).filter(Boolean))] : [], recentCategorySlugs:Array.isArray(rawValue.recentCategorySlugs) ? [...new Set(rawValue.recentCategorySlugs.map((item)=>String(item).trim()).filter(Boolean))].slice(0,6) : [] }; }
function persist(state: DuasState): void { storage.setItem(STORAGE_KEYS.duas, { selectedCategorySlug:state.selectedCategorySlug, searchQuery:state.searchQuery, completedByDate:trimRecordToRecentDays(state.completedByDate,180), favoriteIds:state.favoriteIds, recentCategorySlugs:state.recentCategorySlugs.slice(0,6) }); }
function chooseSelectedCategorySlug(categories: DuaCategory[], preferredSlug: string | null): string | null { if(categories.length===0) return null; if(preferredSlug && categories.some((category)=>category.slug===preferredSlug)) return preferredSlug; return categories[0]?.slug ?? null; }
function mergeLoadedCategories(categories: DuaCategory[], loadedCategories: LoadedDuaCategory[]): DuaCategory[] { const loadedBySlug=new Map(loadedCategories.map((category)=>[category.slug, category])); return categories.map((category)=>loadedBySlug.get(category.slug) ?? category); }
async function hydrateCategorySlugs(slugs: string[], set: (partial: Partial<DuasState>) => void, get: () => DuasStore): Promise<void> { const uniqueSlugs=[...new Set(slugs.map((slug)=>slug.trim()).filter(Boolean))]; if(uniqueSlugs.length===0) return; const unloadedSlugs=uniqueSlugs.filter((slug)=>{ const category=get().categories.find((item)=>item.slug===slug); return Boolean(category && !category.itemsLoaded); }); if(unloadedSlugs.length===0) return; set({ isLoading:true, error:null }); try { const loadedCategories=await hydrateDuaCategories(unloadedSlugs); const currentState=get(); const nextState: DuasState = { ...currentState, isLoading:false, error:null, categories: mergeLoadedCategories(currentState.categories, loadedCategories) }; persist(nextState); set(nextState); } catch (error) { set({ isLoading:false, error:error instanceof Error ? error.message : 'تعذر تحميل فئة الأدعية.' }); } }
async function hydrateAllCategories(set: (partial: Partial<DuasState>) => void, get: () => DuasStore): Promise<void> { const currentState=get(); if(currentState.categories.length===0 || currentState.categories.every((category)=>category.itemsLoaded)) return; set({ isLoading:true, error:null }); try { const categories=await ensureAllDuaCategoriesLoaded(); const nextState: DuasState = { ...get(), isLoading:false, error:null, categories, selectedCategorySlug: chooseSelectedCategorySlug(categories, get().selectedCategorySlug) }; persist(nextState); set(nextState); } catch (error) { set({ isLoading:false, error:error instanceof Error ? error.message : 'تعذر تحميل كل فئات الأدعية.' }); } }
export const useDuasStore = create<DuasStore>((set, get) => ({ ...fallbackState, initialize: () => { if(get().isInitialized) return; const stored=storage.getItem<PersistedDuasState>(STORAGE_KEYS.duas); set({ ...fallbackState, ...normalizePersistedState(stored), isInitialized:true }); }, ensureLoaded: async () => { const state=get(); if(state.isLoading || state.categories.length>0) return; set({ isLoading:true, error:null }); try { const categories=await loadDuaCategorySummaries(); const currentState=get(); const selectedCategorySlug=chooseSelectedCategorySlug(categories,currentState.selectedCategorySlug); const nextState: DuasState = { ...currentState, isLoading:false, error:null, categories, selectedCategorySlug }; persist(nextState); set(nextState); await hydrateCategorySlugs([selectedCategorySlug ?? '', ...currentState.recentCategorySlugs], set, get); } catch (error) { set({ isLoading:false, error:error instanceof Error ? error.message : 'تعذر تحميل الأدعية.' }); } }, setSearchQuery: (query) => { const nextState={ ...get(), searchQuery:query }; persist(nextState); set(nextState); if(query.trim()) void hydrateAllCategories(set,get); }, setSelectedCategory: (slug) => { const normalizedSlug=slug.trim(); if(!normalizedSlug) return; const state=get(); const nextState={ ...state, selectedCategorySlug:normalizedSlug, recentCategorySlugs:[normalizedSlug, ...state.recentCategorySlugs.filter((item)=>item!==normalizedSlug)].slice(0,6) }; persist(nextState); set(nextState); void hydrateCategorySlugs([normalizedSlug], set, get); }, toggleItemCompleted: (itemId) => { const normalizedItemId=itemId.trim(); if(!normalizedItemId) return; const state=get(); const todayKey=getLocalDateKey(); const completed=new Set(state.completedByDate[todayKey] ?? []); if(completed.has(normalizedItemId)) completed.delete(normalizedItemId); else completed.add(normalizedItemId); const nextState={ ...state, completedByDate:{ ...state.completedByDate, [todayKey]: [...completed] } }; persist(nextState); set(nextState); }, toggleFavorite: (itemId) => { const normalizedItemId=itemId.trim(); if(!normalizedItemId) return; const state=get(); const favorites=new Set(state.favoriteIds); if(favorites.has(normalizedItemId)) favorites.delete(normalizedItemId); else favorites.add(normalizedItemId); const nextState={ ...state, favoriteIds:[...favorites] }; persist(nextState); set(nextState); }, resetTodayProgress: () => { const state=get(); const todayKey=getLocalDateKey(); const nextState={ ...state, completedByDate:{ ...state.completedByDate, [todayKey]: [] } }; persist(nextState); set(nextState); } }));
