import { AZKAR_CATEGORY_LOADERS, AZKAR_CATEGORY_SUMMARY } from '@/content/azkar/generated/registry.js';
import { compareSearchRank, normalizeSearchTerm, scoreSearchMatch } from '@/shared/lib/search';
export interface LoadedZikrItem { id: string; legacyId: number; categorySlug: string; categoryTitle: string; text: string; repeatTarget: number; reference?: string; }
export interface LoadedZikrCategory { slug: string; title: string; itemCount: number; preview?: string; itemIds: string[]; itemsLoaded: boolean; items: LoadedZikrItem[]; }
interface LoadedZikrCategoryModule { default?: LoadedZikrCategory; AZKAR_CATEGORY?: LoadedZikrCategory; }
const summaryCache = AZKAR_CATEGORY_SUMMARY.map((category) => ({ ...category }));
const categoryCache = new Map<string, LoadedZikrCategory>();
let allCategoriesCache: LoadedZikrCategory[] | null = null;
function cloneCategory(category: LoadedZikrCategory): LoadedZikrCategory { return { ...category, itemIds:[...category.itemIds], items:category.items.map((item)=>({ ...item })) }; }
function getSummaryCategories(): LoadedZikrCategory[] { return summaryCache.map((category)=>cloneCategory(category)); }
async function loadCategoryModule(slug: string): Promise<LoadedZikrCategory | null> { const cached=categoryCache.get(slug); if(cached) return cloneCategory(cached); const loader=AZKAR_CATEGORY_LOADERS[slug as keyof typeof AZKAR_CATEGORY_LOADERS]; if(!loader) return null; const mod=(await loader()) as LoadedZikrCategoryModule; const category=mod.AZKAR_CATEGORY ?? mod.default ?? null; if(!category) return null; categoryCache.set(slug,category); return cloneCategory(category); }
function mergeSummariesWithLoaded(loadedBySlug: Map<string, LoadedZikrCategory>): LoadedZikrCategory[] { return summaryCache.map((summary)=>{ const loaded=loadedBySlug.get(summary.slug); return loaded ? cloneCategory(loaded) : cloneCategory(summary); }); }
export async function loadAzkarCategories(): Promise<LoadedZikrCategory[]> { if(allCategoriesCache) return allCategoriesCache.map((category)=>cloneCategory(category)); const loadedCategories=await Promise.all(summaryCache.map((category)=>loadCategoryModule(category.slug))); const loadedBySlug=new Map(loadedCategories.filter((category): category is LoadedZikrCategory => Boolean(category)).map((category)=>[category.slug,category])); allCategoriesCache=mergeSummariesWithLoaded(loadedBySlug); return allCategoriesCache.map((category)=>cloneCategory(category)); }
export async function loadAzkarCategorySummaries(): Promise<LoadedZikrCategory[]> { return getSummaryCategories(); }
export async function loadAzkarCategoryBySlug(slug: string): Promise<LoadedZikrCategory | null> { return loadCategoryModule(slug); }
export async function hydrateAzkarCategories(slugs: string[]): Promise<LoadedZikrCategory[]> { const loaded=await Promise.all([...new Set(slugs.map((slug)=>slug.trim()).filter(Boolean))].map((slug)=>loadCategoryModule(slug))); return loaded.filter((category): category is LoadedZikrCategory => Boolean(category)); }
export async function ensureAllAzkarCategoriesLoaded(): Promise<LoadedZikrCategory[]> { return loadAzkarCategories(); }
export function filterLoadedAzkarCategories(categories: LoadedZikrCategory[], query: string): LoadedZikrCategory[] { const normalizedQuery=normalizeSearchTerm(query); if(!normalizedQuery) return categories; return categories.map((category)=>{ const categoryScore=scoreSearchMatch(normalizedQuery, category.title); const rankedItems=category.items.map((item)=>({ score:scoreSearchMatch(normalizedQuery, item.text, item.reference ?? '', item.categoryTitle), item })).filter((entry)=>entry.score>0).sort((left,right)=>compareSearchRank({ score:left.score, value:left.item }, { score:right.score, value:right.item })); if(categoryScore===0 && rankedItems.length===0) return null; const items=categoryScore>0 ? category.items.map((item)=>({ ...item })) : rankedItems.map((entry)=>({ ...entry.item })); return { ...category, itemCount:items.length, itemIds:items.map((item)=>item.id), items, itemsLoaded:category.itemsLoaded, __score:Math.max(categoryScore, rankedItems[0]?.score ?? 0) } as LoadedZikrCategory & { __score:number }; }).filter((category): category is LoadedZikrCategory & { __score:number } => Boolean(category)).sort((left,right)=>right.__score - left.__score || left.title.localeCompare(right.title,'ar')).map(({ __score, ...category })=>category); }
