import { DUA_CATEGORY_LOADERS, DUA_CATEGORY_SUMMARY } from '@/content/duas/generated/registry.js';
import { compareSearchRank, normalizeSearchTerm, scoreSearchMatch } from '@/shared/lib/search';
export interface LoadedDuaItem { id: string; text: string; reference: string | null; source: string | null; repeatTarget: number | null; description: string | null; originalCategory: string | null; }
export interface LoadedDuaCategory { slug: string; title: string; itemCount: number; preview: string; sources: string[]; itemIds: string[]; itemsLoaded: boolean; items: LoadedDuaItem[]; }
interface LoadedDuaCategoryModule { default?: LoadedDuaCategory; DUA_CATEGORY?: LoadedDuaCategory; }
const summaryCache = DUA_CATEGORY_SUMMARY.map((category) => ({ ...category }));
const categoryCache = new Map<string, LoadedDuaCategory>();
let allCategoriesCache: LoadedDuaCategory[] | null = null;
function cloneCategory(category: LoadedDuaCategory): LoadedDuaCategory { return { ...category, sources:[...category.sources], itemIds:[...category.itemIds], items:category.items.map((item)=>({ ...item })) }; }
function getSummaryCategories(): LoadedDuaCategory[] { return summaryCache.map((category)=>cloneCategory(category)); }
async function loadCategoryModule(slug: string): Promise<LoadedDuaCategory | null> { const cached=categoryCache.get(slug); if(cached) return cloneCategory(cached); const loader=DUA_CATEGORY_LOADERS[slug as keyof typeof DUA_CATEGORY_LOADERS]; if(!loader) return null; const mod=(await loader()) as LoadedDuaCategoryModule; const category=mod.DUA_CATEGORY ?? mod.default ?? null; if(!category) return null; categoryCache.set(slug,category); return cloneCategory(category); }
function mergeSummariesWithLoaded(loadedBySlug: Map<string, LoadedDuaCategory>): LoadedDuaCategory[] { return summaryCache.map((summary)=>{ const loaded=loadedBySlug.get(summary.slug); return loaded ? cloneCategory(loaded) : cloneCategory(summary); }); }
export async function loadDuaCategories(): Promise<LoadedDuaCategory[]> { if(allCategoriesCache) return allCategoriesCache.map((category)=>cloneCategory(category)); const loadedCategories=await Promise.all(summaryCache.map((category)=>loadCategoryModule(category.slug))); const loadedBySlug=new Map(loadedCategories.filter((category): category is LoadedDuaCategory => Boolean(category)).map((category)=>[category.slug,category])); allCategoriesCache=mergeSummariesWithLoaded(loadedBySlug); return allCategoriesCache.map((category)=>cloneCategory(category)); }
export async function loadDuaCategorySummaries(): Promise<LoadedDuaCategory[]> { return getSummaryCategories(); }
export async function loadDuaCategoryBySlug(slug: string): Promise<LoadedDuaCategory | null> { return loadCategoryModule(slug); }
export async function hydrateDuaCategories(slugs: string[]): Promise<LoadedDuaCategory[]> { const loaded=await Promise.all(slugs.map((slug)=>loadCategoryModule(slug))); return loaded.filter((category): category is LoadedDuaCategory => Boolean(category)); }
export async function ensureAllDuaCategoriesLoaded(): Promise<LoadedDuaCategory[]> { return loadDuaCategories(); }
export function filterLoadedDuaCategories(categories: LoadedDuaCategory[], query: string): LoadedDuaCategory[] { const normalizedQuery=normalizeSearchTerm(query); if(!normalizedQuery) return categories; return categories.map((category)=>{ const categoryScore=scoreSearchMatch(normalizedQuery, category.title, category.preview, ...category.sources); const itemScore=category.items.reduce((best,item)=>{ const score=scoreSearchMatch(normalizedQuery, item.text, item.reference ?? '', item.originalCategory ?? '', item.source ?? '', item.description ?? ''); return score > best ? score : best; },0); const score=Math.max(categoryScore,itemScore); if(score===0) return null; return { ...category, __score:score } as LoadedDuaCategory & { __score:number }; }).filter((category): category is LoadedDuaCategory & { __score:number } => Boolean(category)).sort((left,right)=>right.__score - left.__score || left.title.localeCompare(right.title,'ar')).map(({ __score, ...category })=>category); }
export async function loadDuasSummary(): Promise<{ categoryCount: number; itemCount: number; featuredDua: string }> { const categories=await loadDuaCategorySummaries(); const itemCount=categories.reduce((sum, category)=>sum + category.itemCount, 0); return { categoryCount: categories.length, itemCount, featuredDua: categories[0]?.preview ?? 'لا يوجد دعاء مميز حالياً.' }; }
