import { DUA_CATEGORY_LOADERS, DUA_CATEGORY_SUMMARY } from '@/content/duas/generated/registry.js';
export interface LoadedDuaItem { id: string; text: string; reference: string | null; source: string | null; repeatTarget: number | null; description: string | null; originalCategory: string | null; }
export interface LoadedDuaCategory { slug: string; title: string; itemCount: number; preview: string; sources: string[]; itemIds: string[]; itemsLoaded: boolean; items: LoadedDuaItem[]; }
interface LoadedDuaCategoryModule { default?: LoadedDuaCategory; DUA_CATEGORY?: LoadedDuaCategory; }
const summaryCache = DUA_CATEGORY_SUMMARY.map((category) => ({ ...category }));
const categoryCache = new Map<string, LoadedDuaCategory>();
let allCategoriesCache: LoadedDuaCategory[] | null = null;
function cloneCategory(category: LoadedDuaCategory): LoadedDuaCategory { return { ...category, sources:[...category.sources], itemIds:[...category.itemIds], items:category.items.map((item)=>({ ...item })) }; }
function normalizeQuery(query: string): string { return query.trim().toLowerCase(); }
function getSummaryCategories(): LoadedDuaCategory[] { return summaryCache.map((category)=>cloneCategory(category)); }
async function loadCategoryModule(slug: string): Promise<LoadedDuaCategory | null> { const cached=categoryCache.get(slug); if(cached) return cloneCategory(cached); const loader=DUA_CATEGORY_LOADERS[slug as keyof typeof DUA_CATEGORY_LOADERS]; if(!loader) return null; const mod=(await loader()) as LoadedDuaCategoryModule; const category=mod.DUA_CATEGORY ?? mod.default ?? null; if(!category) return null; categoryCache.set(slug,category); return cloneCategory(category); }
function mergeSummariesWithLoaded(loadedBySlug: Map<string, LoadedDuaCategory>): LoadedDuaCategory[] { return summaryCache.map((summary)=>{ const loaded=loadedBySlug.get(summary.slug); return loaded ? cloneCategory(loaded) : cloneCategory(summary); }); }
export async function loadDuaCategories(): Promise<LoadedDuaCategory[]> { if(allCategoriesCache) return allCategoriesCache.map((category)=>cloneCategory(category)); const loadedCategories=await Promise.all(summaryCache.map((category)=>loadCategoryModule(category.slug))); const loadedBySlug=new Map(loadedCategories.filter((category): category is LoadedDuaCategory => Boolean(category)).map((category)=>[category.slug,category])); allCategoriesCache=mergeSummariesWithLoaded(loadedBySlug); return allCategoriesCache.map((category)=>cloneCategory(category)); }
export async function loadDuaCategorySummaries(): Promise<LoadedDuaCategory[]> { return getSummaryCategories(); }
export async function loadDuaCategoryBySlug(slug: string): Promise<LoadedDuaCategory | null> { return loadCategoryModule(slug); }
export async function hydrateDuaCategories(slugs: string[]): Promise<LoadedDuaCategory[]> { const loaded=await Promise.all(slugs.map((slug)=>loadCategoryModule(slug))); return loaded.filter((category): category is LoadedDuaCategory => Boolean(category)); }
export async function ensureAllDuaCategoriesLoaded(): Promise<LoadedDuaCategory[]> { return loadDuaCategories(); }
export function filterLoadedDuaCategories(categories: LoadedDuaCategory[], query: string): LoadedDuaCategory[] { const normalizedQuery=normalizeQuery(query); if(!normalizedQuery) return categories; return categories.filter((category)=>{ if(category.title.toLowerCase().includes(normalizedQuery)) return true; return category.items.some((item)=>[item.text, item.reference ?? '', item.originalCategory ?? '', item.source ?? ''].some((value)=>value.toLowerCase().includes(normalizedQuery))); }); }
export async function loadDuasSummary(): Promise<{ categoryCount: number; itemCount: number; featuredDua: string }> { const categories=await loadDuaCategorySummaries(); const itemCount=categories.reduce((sum, category)=>sum + category.itemCount, 0); return { categoryCount: categories.length, itemCount, featuredDua: categories[0]?.preview ?? 'لا يوجد دعاء مميز حالياً.' }; }
