import type { AppSection } from '@/kernel/sections/section-contract';

export const appSections: AppSection[] = [
  {
    key: 'home',
    route: '/',
    title: 'الرئيسية',
    shortTitle: 'الرئيسية',
    description: 'واجهة توزيع حديثة للمحتوى والمهمات الحالية وحالة الهجرة.',
    icon: '⌂',
    order: 0,
    showInBottomNav: true,
    loader: () => import('@/features/home/pages/HomePage').then((mod) => ({ default: mod.HomePage })),
  },
  {
    key: 'azkar',
    route: '/azkar',
    title: 'الأذكار',
    shortTitle: 'الأذكار',
    description: 'تصنيفات الأذكار اليومية مع فصل منطقي عن باقي الأقسام.',
    icon: '☀',
    order: 1,
    showInBottomNav: true,
    loader: () => import('@/features/azkar/pages/AzkarPage').then((mod) => ({ default: mod.AzkarPage })),
  },
  {
    key: 'masbaha',
    route: '/masbaha',
    title: 'المسبحة',
    shortTitle: 'المسبحة',
    description: 'counter module معزول وقابل للتوسع لاحقًا.',
    icon: '•',
    order: 2,
    showInBottomNav: true,
    loader: () => import('@/features/masbaha/pages/MasbahaPage').then((mod) => ({ default: mod.MasbahaPage })),
  },
  {
    key: 'quran',
    route: '/quran',
    title: 'القرآن',
    shortTitle: 'القرآن',
    description: 'فهرس خفيف، تحميل السور عند الطلب، وbookmark/resume داخل store مستقلة.',
    icon: '۞',
    order: 3,
    showInBottomNav: true,
    loader: () => import('@/features/quran/pages/QuranPage').then((mod) => ({ default: mod.QuranPage })),
  },
  {
    key: 'tasks',
    route: '/tasks',
    title: 'المهام',
    shortTitle: 'المهام',
    description: 'لوحة مهام فعلية داخل البنية الجديدة.',
    icon: '✓',
    order: 4,
    showInBottomNav: true,
    loader: () => import('@/features/tasks/pages/TasksPage').then((mod) => ({ default: mod.TasksPage })),
  },
  {
    key: 'stats',
    route: '/stats',
    title: 'الإحصائيات',
    shortTitle: 'الإحصائيات',
    description: 'derived analytics فوق stores المختلفة.',
    icon: '≋',
    order: 5,
    showInBottomNav: true,
    loader: () => import('@/features/stats/pages/StatsPage').then((mod) => ({ default: mod.StatsPage })),
  },
  {
    key: 'duas',
    route: '/duas',
    title: 'الأدعية',
    shortTitle: 'الأدعية',
    description: 'محتوى الأدعية مبني على loaders منفصلة عن الواجهة.',
    icon: '✦',
    order: 6,
    showInBottomNav: false,
    loader: () => import('@/features/duas/pages/DuasPage').then((mod) => ({ default: mod.DuasPage })),
  },
  {
    key: 'names',
    route: '/names-of-allah',
    title: 'أسماء الله الحسنى',
    shortTitle: 'الأسماء',
    description: 'أسماء الله الحسنى ضمن module مستقلة مع search + favorites + daily progress.',
    icon: '99',
    order: 7,
    showInBottomNav: false,
    loader: () => import('@/features/names-of-allah/pages/NamesOfAllahPage').then((mod) => ({ default: mod.NamesOfAllahPage })),
  },
  {
    key: 'stories',
    route: '/stories',
    title: 'القصص',
    shortTitle: 'القصص',
    description: 'قصص مختارة ضمن module مستقل قابل للتطوير.',
    icon: '☰',
    order: 8,
    showInBottomNav: false,
    loader: () => import('@/features/stories/pages/StoriesPage').then((mod) => ({ default: mod.StoriesPage })),
  },
  {
    key: 'settings',
    route: '/settings',
    title: 'الإعدادات',
    shortTitle: 'الإعدادات',
    description: 'التفضيلات وتسجيل الدخول فقط بدون خلط مع profile.',
    icon: '⚙',
    order: 9,
    showInBottomNav: false,
    loader: () => import('@/features/settings/pages/SettingsPage').then((mod) => ({ default: mod.SettingsPage })),
  },
  {
    key: 'profile',
    route: '/profile',
    title: 'الملف الشخصي',
    shortTitle: 'الملف',
    description: 'عرض بيانات المستخدم المعتمد فقط.',
    icon: '☺',
    order: 10,
    showInBottomNav: false,
    loader: () => import('@/features/profile/pages/ProfilePage').then((mod) => ({ default: mod.ProfilePage })),
  },
  {
    key: 'about',
    route: '/about',
    title: 'عن التطبيق',
    shortTitle: 'عن التطبيق',
    description: 'صفحة موحدة داخل التطبيق تشرح النسخة الحالية، حدودها، واتجاه التطوير.',
    icon: 'ℹ',
    order: 11,
    showInBottomNav: false,
    loader: () => import('@/features/legal/pages/AboutPage').then((mod) => ({ default: mod.AboutPage })),
  },
  {
    key: 'privacy',
    route: '/privacy',
    title: 'سياسة الخصوصية',
    shortTitle: 'الخصوصية',
    description: 'كيف تُخزن البيانات محليًا وكيف يُستخدم تسجيل الدخول في النسخة الحالية.',
    icon: '🔒',
    order: 12,
    showInBottomNav: false,
    loader: () => import('@/features/legal/pages/PrivacyPage').then((mod) => ({ default: mod.PrivacyPage })),
  },
  {
    key: 'terms',
    route: '/terms',
    title: 'شروط الاستخدام',
    shortTitle: 'الشروط',
    description: 'الحدود العامة لاستخدام التطبيق والمحتوى ضمن المسار الحالي.',
    icon: '§',
    order: 13,
    showInBottomNav: false,
    loader: () => import('@/features/legal/pages/TermsPage').then((mod) => ({ default: mod.TermsPage })),
  },
  {
    key: 'contact',
    route: '/contact',
    title: 'تواصل معنا',
    shortTitle: 'تواصل',
    description: 'قنوات التواصل الرسمية والصفحات المساندة أصبحت داخل التطبيق نفسه.',
    icon: '✉',
    order: 14,
    showInBottomNav: false,
    loader: () => import('@/features/legal/pages/ContactPage').then((mod) => ({ default: mod.ContactPage })),
  },
].sort((left, right) => left.order - right.order);
